function references = study_build_reference_library(context)
t = (0:(context.reference_horizon - 1)) * context.params.simTimeStep;
rotation_columns = repmat(reshape(eye(3), 9, 1), 1, numel(t));
zero_body_rates = zeros(3, numel(t));

hover_target = [0.75; -0.50; 1.00];
hover_position = zeros(3, numel(t));
hover_position(:, t >= 0.25) = repmat(hover_target, 1, sum(t >= 0.25));
hover_velocity = zeros(3, numel(t));
hover_reference = [hover_position; hover_velocity; rotation_columns; zero_body_rates];

radius = 0.80;
omega_planar = 1.35;
planar_position = [ ...
    radius * (1 - cos(omega_planar * t)); ...
    radius * sin(omega_planar * t); ...
    0.70 * (1 - cos(0.5 * omega_planar * t))];
planar_velocity = [ ...
    radius * omega_planar * sin(omega_planar * t); ...
    radius * omega_planar * cos(omega_planar * t); ...
    0.35 * omega_planar * sin(0.5 * omega_planar * t)];
planar_reference = [planar_position; planar_velocity; rotation_columns; zero_body_rates];

omega_fast = 2.80;
aggressive_position = [ ...
    0.85 * sin(omega_fast * t); ...
    0.60 * sin(1.6 * omega_fast * t); ...
    0.65 * (1 - cos(1.25 * omega_fast * t))];
aggressive_velocity = [ ...
    0.85 * omega_fast * cos(omega_fast * t); ...
    0.96 * omega_fast * cos(1.6 * omega_fast * t); ...
    0.8125 * omega_fast * sin(1.25 * omega_fast * t)];
aggressive_reference = [aggressive_position; aggressive_velocity; rotation_columns; zero_body_rates];

references(1) = study_build_reference_struct('hover_setpoint', 'Hover / Setpoint', hover_reference, context);
references(2) = study_build_reference_struct('smooth_planar', 'Smooth Planar / Circular', planar_reference, context);
references(3) = study_build_reference_struct('aggressive_multi_axis', 'Aggressive Multi-Axis', aggressive_reference, context);
end
